overrides:
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  devalue@<5.3.2: '>=5.3.2'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  nanoid@<3.3.8: '>=3.3.8'
  undici@>=6.0.0 <6.21.1: '>=6.21.1'
  undici@>=6.0.0 <6.21.2: '>=6.21.2'
